### ISSUE TITLE
"QtQuick" version 2.5 is not installed

### ISSUE THREAD

**Issue by jazzgroove** [TheLastProject/Pext#2]
Hi,

Despite all dependencies being installed, I receive the following error when trying to run the app:

Pext/main.qml:18 module "QtQuick" version 2.5 is not installed

I'm running this on Debian Jessie.

**Comment by TheLastProject** [comment]
Thanks for the report.

I've spent the last day or so researching this and, unless I am mistaking, it seems to be that Debian Jessie's version of Qt is too old.

Looking at the Qt documentation, [Shortcuts](https://doc.qt.io/qt-5/qml-qtquick-shortcut.html), which Pext uses a lot, requires Qt 5.5. Yet, Debian Jessie seems to ship [version 5.3.2 in Jessie](https://packages.debian.org/jessie/qt5-default).

While I understand that Jessie is the current stable, I personally only use Debian Testing, which ships a recent enough Qt version.

I'll do some more research to try to figure out if there is any way to list the installed versions of QML modules to confirm this theory. If I do, I'll come back to this issue to ask you to run something to get the version information. If I don't find a way, I will just add a note to the README stating a newer version than Jessie is likely needed.

**Comment by TheLastProject** [comment]
After more research and from some help of #qt in Freenode, it indeed turns out Debian Jessie has a Qt version that is too outdated for Pext. I've added a note in 0a584b18e72076c9b85e088384be348a01d47821 about that. My apologies for not catching this dependency issue earlier and thanks again for the report.
